apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-scale
  namespace: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/hpa-example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: 500m
              memory: 800Mi
            requests:
              cpu: 300m
              memory: 400Mi
      terminationGracePeriodSeconds: 300
